name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run CI
        uses: ./.github/actions/ci
        with:
          commit-lint-from: ${{ github.event.pull_request.base.sha }}
          commit-lint-to: ${{ github.event.pull_request.head.sha }}
